apiVersion: k8s.starter.org/v1alpha1
kind: KubernetesCluster
metadata:
  name: murph-port-demo
  namespace: default
spec:
  id: murph-port-demo
  parameters:
    nodes:
      count: 1
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: murph-port-demo-kubeconfig
